name: CI

on:
  pull_request:  # any pull request
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: '1'
  NODE_VERSION: '20'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: ${{ env.NODE_VERSION }}
      - uses: finleyfamily/action-setup-python@v1.2.0
      - run: make setup.npm build test
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: make setup.npm
      - run: make build
      - run: make spellcheck
