name: default

on:
  pull_request:  # any pull request
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: '1'
  NODE_VERSION: '20'
  PYTEST_ADDOPTS: --color=yes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: ${{ env.NODE_VERSION }}
      - uses: ITProKyle/action-setup-python@v0.7.0
      - run: make setup-npm build test
